# coverage campaign entry
# rule_key: guardian.1password-service-account-token
ops_eyJNGVW6+LGkaGL0CvcgA2rluONMc7YPzAQPWnWs6xDBmCSVeCJM6mj3YkSqMLT0ks7tT3w3DwOgM5DieZGOSOI2xxzRP1Wbtyz23nd8aO8I81Qb23bypUNxzgU/nq2u31zp+Dxh6pzHjzlu+dMcXE02+/FzkJ4INu1a99zAL6WeM28+PVVKfcis6pFskYuA1KaeZRiwidSJjrWtK69H5Rdbm83wPoMHdzQNh2HxtInktpotFsIiy4/LMQP9V
